# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  deploy_dev:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: git submodule update --init --remote
      - run:
          name: Deployment
          command: bash .circleci/deploy-scripts/deploy_develop.sh
  deploy_staging:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: git submodule update --init --remote
      - run:
          name: Deployment
          command: bash .circleci/deploy-scripts/deploy_staging.sh
  deploy:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: git submodule update --init --remote
      - run:
          name: Deployment
          command: bash .circleci/deploy-scripts/deploy_production.sh
      - run:
          name: New Relic Notification
          command: bash .circleci/deploy-scripts/new_relic_notification.sh
      - run:
          name: Slack Notification
          command: bash .circleci/deploy-scripts/slack_notification.sh

workflows:
  version: 2
  release_dev:
    jobs:
      - deploy_dev:
          filters:
            branches:
              only: /dev-release(?:/.+)?$/
  release_staging:
    jobs:
      - deploy_staging:
          filters:
            branches:
              only: /release(?:/.+)?$/
  release:
    jobs:
      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/